service: aws-budget-notifier

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${file(./config.${self:provider.stage}.yml):region, 'ap-northeast-1'}
  environment:
    LOCALSTACK_HOSTNAME: ${file(./config.${self:provider.stage}.yml):localstack_hostname, 'localhost'}

functions:
  notify_cost:
    handler: handler.main
    events:
      - eventBridge:
          schedule: rate(1 minute)
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - custom.event          

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true