service: budget-notifier

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: local
  region: ${env:REGION}
  environment:
    PYTHONPATH: ${env:PYTHONPATH}
    LOCALSTACK_HOSTNAME: localhost

package:
  individually: true
  exclude:
    - 'node_modules/**'

functions:
  notify_cost:
    handler: src/handler.main
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - custom.event

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true