name: Run Tests

on:
  pull_request:

env:
  PYTHONPATH: src

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.7'
        architecture: 'x64'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
